[package]

name = "racer"
version = "0.0.1"
license = "MIT"
description = "Code completion for Rust"
authors = ["Phil Dawes <phil@phildawes.net>"]

[lib]
name = "racer"
crate_type = ["rlib"]
path = "src/lib.rs"

[profile.release]
debug = true
